Repository gardener/gardener-extension-os-ubuntu, pull requests merged in 2021-06, with the labels that each got.

#40 Use dedicated secret for the sample OSC
  README.md
  example/10-crd-cluster.yaml
  example/10-crd-operatingsystemconfig.yaml
  example/20-cluster.yaml
  example/30-secret.yaml
  example/40-operatingsystemconfig.yaml
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, os/ubuntu, reviewed/lgtm, size/s

#42 Support TransmitUnencoded flag
  pkg/generator/templates/cloud-init-ubuntu.template
  pkg/generator/testfiles/cloud-init
Labels: area/security, kind/enhancement, needs/ok-to-test, os/ubuntu, reviewed/lgtm, size/xs

#43 Update golang to 1.16.5
  Dockerfile
Labels: needs/ok-to-test, os/ubuntu, reviewed/lgtm, size/xs

#45 Small improvement in Github template generation
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/pull_request_template.md
  hack/update-github-templates.sh
Labels: needs/ok-to-test, os/ubuntu, reviewed/lgtm, size/xs
