Repository gardener/gardener-extension-os-ubuntu, pull requests merged in 2022-08, with the labels that each got.

#70 Bump golang to 1.17.13
  Dockerfile
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs, area/os, os/garden-linux

#68 Remove install-requirement and use tools.mk
  .gitignore
  Dockerfile
  Makefile
  hack/tools/bin/.gitkeep
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, area/os, os/ubuntu

#69 assign image responsible
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs, area/os, os/ubuntu
