Repository gardener/gardener-extension-os-ubuntu, pull requests merged in 2023-07, with the labels that each got.

#82 Drop support for Shoots with Kubernetes version < 1.22
  charts/gardener-extension-os-ubuntu/templates/poddisruptionbudget.yaml
  example/controller-registration.yaml
Labels: kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, merge/squash

#83 Introduce persona-based docs
  .docforge/manifest.yaml
  docs/usage/usage.md
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#88 Bump github.com/gardener/gardener from 1.75.1 to 1.76.0
  .github/workflows/vendor_gardener.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/types_etcd.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_reconcile.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_restore.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_util.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/reconciler.go
  vendor/github.com/gardener/gardener/hack/generate-monitoring-docs.sh
  vendor/github.com/gardener/gardener/hack/test-prometheus.sh
  vendor/github.com/gardener/gardener/pkg/apis/core/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/operator/v1alpha1/constants.go
  vendor/github.com/gardener/gardener/pkg/apis/operator/v1alpha1/types.go
  vendor/github.com/gardener/gardener/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/progress_reporter.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/tls_cipher_suites.go
  vendor/github.com/gardener/gardener/pkg/utils/miscellaneous.go
  vendor/modules.txt
Labels: kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m, area/os, os/ubuntu
