Repository gardener/gardener-extension-os-ubuntu, pull requests merged in 2025-08, with the labels that each got.

#215 Fix RBAC when deploying via gardener-operator
  charts/gardener-extension-os-ubuntu/templates/rbac.yaml
  example/controller-registration.yaml
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, area/os

#234 chore: update build status badge
  README.md
Labels: kind/cleanup, reviewed/lgtm, size/xs, area/os, os/ubuntu

#238 Add generation for `Extension` example
  Makefile
  example/doc.go
  example/extension.yaml
  example/extension/base/extension.yaml
  example/extension/base/kustomization.yaml
  example/extension/extension.yaml
  example/extension/kustomization.yaml
Labels: area/ops-productivity, kind/enhancement, reviewed/lgtm, size/s, area/os, os/ubuntu
